USE [master]
GO

/****** Object:  Database [OffersTesting]    Script Date: 10/31/2020 6:56:03 PM ******/
CREATE DATABASE [OffersTesting]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OffersTesting', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVERNEW\MSSQL\DATA\OffersTesting.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OffersTesting_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLSERVERNEW\MSSQL\DATA\OffersTesting_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OffersTesting].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OffersTesting] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OffersTesting] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OffersTesting] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OffersTesting] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OffersTesting] SET ARITHABORT OFF 
GO

ALTER DATABASE [OffersTesting] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OffersTesting] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OffersTesting] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OffersTesting] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OffersTesting] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OffersTesting] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OffersTesting] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OffersTesting] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OffersTesting] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OffersTesting] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OffersTesting] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OffersTesting] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OffersTesting] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OffersTesting] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OffersTesting] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OffersTesting] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OffersTesting] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OffersTesting] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [OffersTesting] SET  MULTI_USER 
GO

ALTER DATABASE [OffersTesting] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OffersTesting] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OffersTesting] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OffersTesting] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OffersTesting] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OffersTesting] SET QUERY_STORE = OFF
GO

ALTER DATABASE [OffersTesting] SET  READ_WRITE 
GO

