//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OffersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffersInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OffersInventory()
        {
            this.OfferContents = new HashSet<OfferContent>();
        }
    
        public int OfferId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public int SortOrder { get; set; }
        public string Target { get; set; }
        public int PricingId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferContent> OfferContents { get; set; }
        public virtual PricingDetail PricingDetail { get; set; }
    }
}
