//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OffersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferContent
    {
        public int OfferId { get; set; }
        public int ItemId { get; set; }
        public int quantity { get; set; }
    
        public virtual OffersInventory OffersInventory { get; set; }
    }
}
